name: Format and Lint

on:
  push:
    branches: [ main ]

jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter format
      - run: flutter analyze
